/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Rich-UI",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "https://artice-code-1258339218.cos.ap-beijing.myqcloud.com/vuepress/element-index.png",
        "heroText": "Rich-UI",
        "features": [
          {
            "title": "一致性 Consistency",
            "details": "与现实生活一致：与现实生活的流程、逻辑保持一致，遵循用户习惯的语言和概念"
          },
          {
            "title": "反馈 Feedback",
            "details": "通过界面样式和交互动效让用户可以清晰的感知自己的操作"
          },
          {
            "title": "效率 Efficiency",
            "details": "界面简单直白，让用户快速识别而非回忆，减少用户记忆负担。"
          }
        ],
        "footer": "by饿了么"
      },
      "regularPath": "/en/",
      "relativePath": "en/README.md",
      "key": "v-928b0ccc",
      "path": "/en/",
      "headers": [
        {
          "level": 3,
          "title": "设计原则",
          "slug": "设计原则"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/en/components/install.html",
      "relativePath": "en/components/install.md",
      "key": "v-7ec7eef8",
      "path": "/en/components/install.html"
    },
    {
      "title": "Button 按钮",
      "frontmatter": {},
      "regularPath": "/en/components/button.html",
      "relativePath": "en/components/button.md",
      "key": "v-26ea9634",
      "path": "/en/components/button.html",
      "headers": [
        {
          "level": 2,
          "title": "Button 按钮",
          "slug": "button-按钮"
        },
        {
          "level": 3,
          "title": "基础用法",
          "slug": "基础用法"
        },
        {
          "level": 3,
          "title": "基础用法2",
          "slug": "基础用法2"
        }
      ]
    },
    {
      "title": "指南",
      "frontmatter": {},
      "regularPath": "/en/guide/guide.html",
      "relativePath": "en/guide/guide.md",
      "key": "v-7d0b3a38",
      "path": "/en/guide/guide.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "https://artice-code-1258339218.cos.ap-beijing.myqcloud.com/vuepress/element-index.png",
        "heroText": "Rich-UI",
        "features": [
          {
            "title": "一致性 Consistency",
            "details": "与现实生活一致：与现实生活的流程、逻辑保持一致，遵循用户习惯的语言和概念"
          },
          {
            "title": "反馈 Feedback",
            "details": "通过界面样式和交互动效让用户可以清晰的感知自己的操作"
          },
          {
            "title": "效率 Efficiency",
            "details": "界面简单直白，让用户快速识别而非回忆，减少用户记忆负担。"
          }
        ],
        "footer": "by饿了么"
      },
      "regularPath": "/zh/",
      "relativePath": "zh/README.md",
      "key": "v-1c8d7d7a",
      "path": "/zh/",
      "headers": [
        {
          "level": 3,
          "title": "设计原则",
          "slug": "设计原则"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/components/install.html",
      "relativePath": "zh/components/install.md",
      "key": "v-a284cfb8",
      "path": "/zh/components/install.html"
    },
    {
      "title": "Button 按钮",
      "frontmatter": {},
      "regularPath": "/zh/components/button.html",
      "relativePath": "zh/components/button.md",
      "key": "v-7801839c",
      "path": "/zh/components/button.html",
      "headers": [
        {
          "level": 2,
          "title": "Button 按钮",
          "slug": "button-按钮"
        },
        {
          "level": 3,
          "title": "基础用法",
          "slug": "基础用法"
        },
        {
          "level": 3,
          "title": "基础用法2",
          "slug": "基础用法2"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebarDepth": 2,
    "locales": {
      "/en/": {
        "nav": [
          {
            "text": "guide",
            "link": "/en/guide/guide"
          },
          {
            "text": "components",
            "link": "/en/components/install"
          },
          {
            "text": "External",
            "link": "https://www.baidu.com"
          }
        ],
        "sidebar": {
          "/en/components/": [
            [
              "/en/components/install",
              "安装"
            ],
            [
              "/en/components/button",
              "按钮"
            ]
          ]
        }
      },
      "/zh/": {
        "nav": [
          {
            "text": "指南",
            "link": "/zh/guide/guide"
          },
          {
            "text": "组件",
            "link": "/zh/components/install"
          },
          {
            "text": "百度",
            "link": "https://www.baidu.com"
          }
        ],
        "sidebar": {
          "/zh/components/": [
            [
              "/zh/components/install",
              "安装"
            ],
            [
              "/zh/components/button",
              "按钮"
            ]
          ]
        }
      }
    }
  },
  "locales": {
    "/en/": {
      "lang": "en-US",
      "path": "/en/"
    },
    "/zh/": {
      "lang": "zh-CN",
      "path": "/zh/"
    }
  }
}