/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "rich-ui",
  "description": "开始你的组件化之旅吧~",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/components/button.html",
      "relativePath": "components/button.md",
      "key": "v-2f6710b1",
      "path": "/components/button.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/components/install.html",
      "relativePath": "components/install.md",
      "key": "v-22e3e9f9",
      "path": "/components/install.html"
    },
    {
      "title": "指南",
      "frontmatter": {},
      "regularPath": "/guide/guide.html",
      "relativePath": "guide/guide.md",
      "key": "v-82cfe412",
      "path": "/guide/guide.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "指南",
        "link": "/guide/guide"
      },
      {
        "text": "组件",
        "link": "/components/install"
      },
      {
        "text": "External",
        "link": "https://www.baidu.com"
      }
    ],
    "sidebar": {
      "/components/": [
        [
          "/components/install",
          "安装"
        ],
        [
          "/components/button",
          "按钮"
        ]
      ]
    }
  }
}